---
kind: "operation"
client: "rug-cli 0.17.1"
editor:
  name: "atomist-rugs.travis-editors.EnableTravisForRugArchiveDSL"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.4.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "ffa56d6"
  parameters:
    - "repo_slug": "atomist-rugs/rug-editors"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.19.1"
editor:
  name: "UpgradeFrom0_7_1"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "atomist-rugs/rug-upgrade"
    branch: "master"
    sha: "e556ba9*"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.20.0"
editor:
  name: "atomist-rugs.rug-editors.AddRugEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.4.0"
  origin:
    repo: "atomist-rugs/rug-editors"
    branch: "master"
    sha: "17eefad*"
  parameters:
    - "editor_name": "AddTypescriptEditor"

---
kind: "operation"
client: "rug-cli 0.23.0"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.9.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "2ded1a9*"
  parameters:
    - "editor_name": "AddTypeScriptGenerator"
    - "rug_version": "0.12.0"

---
kind: "operation"
client: "rug-cli 0.23.0"
editor:
  name: "atomist-rugs.rug-editors.AddRugEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.10.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "addHandlerEditor"
    sha: "b8650ae"
  parameters:
    - "editor_name": "AddAtomistCopyright"

---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.9.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "82acbef9ce2c04e0cb6316b9fde702a89469a85b"
    sha: "82acbef"
  parameters:
    - "editor_name": "AddTypeScript"
    - "description": "adds TypeScript supporting files to a Rug archive project"

---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.11.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "116c022*"
  parameters:
    - "editor_name": "ConvertExistingProjectToRugArchive"
    - "description": "add Rug archive files to an existing project"

---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.11.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "116c022*"
  parameters:
    - "editor_name": "AddManifestYml"
    - "description": "add Rug archive manifest"
---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.11.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "116c022*"
  parameters:
    - "editor_name": "AddTypeScriptExecutor"
    - "description": "add TypeScript Rug executor to project"

---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.11.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "116c022*"
  parameters:
    - "editor_name": "AddTypeScriptHandler"
    - "description": "add TypeScript Rug handler to project"

---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.11.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "116c022*"
  parameters:
    - "editor_name": "AddTypeScriptEditor"
    - "description": "add TypeScript Rug editor to project"

---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.11.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "116c022*"
  parameters:
    - "editor_name": "UpdateRugVersion"
    - "description": "update Rug archive Rug dependency version"

---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.11.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors"
    branch: "master"
    sha: "e9ca710*"
  parameters:
    - "editor_name": "HavePathExpressionEngine"
    - "description": "get access to a path expression engine in a Rug editor"

---
kind: "operation"
client: "rug-cli 0.25.0"
editor:
  name: "AddTypeScriptEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.16.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors"
    branch: "master"
    sha: "2f43ffb"
  parameters:
    - "editor_name": "AddLocalEditor"
    - "description": "make an editor for modifying the local project, initiating a rug archive if needed"

---
kind: "operation"
client: "rug-cli 0.25.0"
editor:
  name: "TestsToTypeScript"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.3.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-upgrade.git"
    branch: "master"
    sha: "8b4f0e5*"

---
kind: "operation"
client: "rug-cli 0.25.0"
editor:
  name: "TestsToTypeScript"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.4.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-upgrade.git"
    branch: "master"
    sha: "9800ee6*"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-m.4"
editor:
  name: "ConvertManifestToPackageJson"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.0"
  origin:
    repo: "git@github.com:atomist/rug-rugs.git"
    branch: "master"
    sha: "d1145f3"

