---
kind: "operation"
client: "rug-cli 0.17.1"
editor:
  name: "atomist-rugs.travis-editors.EnableTravisForRugArchiveDSL"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.4.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "ffa56d6"
  parameters:
    - "repo_slug": "atomist-rugs/rug-editors"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.19.1"
editor:
  name: "UpgradeFrom0_7_1"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "atomist-rugs/rug-upgrade"
    branch: "master"
    sha: "e556ba9*"

---
kind: "operation"
<<<<<<< Updated upstream
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"
=======
client: "rug-cli 0.20.0"
editor:
  name: "atomist-rugs.rug-editors.AddRugEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.4.0"
  origin:
    repo: "atomist-rugs/rug-editors"
    branch: "master"
    sha: "17eefad*"
  parameters:
    - "editor_name": "AddTypescriptEditor"
>>>>>>> Stashed changes

