dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: SDp2lQm4iWFyeEijHdkeExivotvsySCMLDlsBuY47T+V+Mr+dKRTUTVCToP1lsRuqrE+rnDHPnDUYaIYfD2CRfqEM1FrdYhcL1knCNlex8KJyIPI8AYYRofFlYNjengG/tActt5C7H2k2MjjgTPChlIn3GTgz2sGaD9CirYfMDUYoECQlBhl69BetZg4rPQntEztyw43UviKik9aZVVvrT5kIeT7cJz8i2B9Si51imlWHQHrmJpahBjV9pPHvL/K3hAQ3htVPuXhHzY5keuzlCdglriYeFB7uTkcKtnz+DK2TNjGFBHSNDBWgn3AMBuzzEehK+5citeEhfi0qbA5u9LLeI5TT+vSTZ1/fdGnS51XIXuYNbTJHCbCvzqQiT1Ywxqir7rL+6nlL/0cV0I+Dtn48zuLxFoyUQN3Msuf+PrVB2WlgFxUrbw3IX1E+gG5uZfwZonXKYh1sBK5Ec0hv+jipy8TLEJTDkcdP1GOq4ttPllKYpLB8eMUl0QOIjX4t0OGtGS03Kj07ot3qi5hr9Xkexb/NY7LL/4sSW5Foku6dHKQqcC27vCeleyrzlibfSA+r5TyEZvMbULwtvHP1xP5/6UfSpor3xWrGTmzVRx2UW5Rb8U/JAQvWmd543NkM/qU8GSZx4pN2PQkjDF+J8u5wTz8YRW2dpWrEky+HgM=
  - secure: Of7Df3EtvzIU5VGPMntIVy/ZT8iEMvar4CxKBjyICzRxui+pPs/4k0j8SeRzcdRqhAHqTsfSf+COoo4jj2pQzEkeK04oBv/6cAIYNRabFlVo6pW2vGPzUQDJbykj6PSKzmwORq+wwRDiXkGiCvaA5SOvI5cCvjqaER7rI9LcS/nQ/lwvYUaXEEku2mt4jV4bgWAg223RTfwk7hcsVIXPxbauB08cZbJBNB/YbiYb20ijIOYFndBuEcQ8YSBfPzIyzAHHWhik2kL/8hZIwlfyvz1GrWuWyAj24Eq5NX8CIyDsKFVBmDvkZU6GLcY1rKITr0GsEOS0dbemeWZ4seKsx08tM8FMXYxz/3HyPiYCjtTOLezJfOd0z5O5IEkD1FKuR01wkBXtmDOlm4AE0EnRSCCEH+DZvVNIjsbAIdWJ3LxotYeKYF5JvxRjT7VavOM3BXXtRksuzpnNF7uLtI9f3ySePNvAtrWMV5VWMOvMiDgWeigK9mAx7RyvoZdbOPKr/Nt9KdT+i8o56ICT8phS/RbbRa6V7qlZQZE/gHyFZvr6sKMpxiw4s2Gjt6zvd8punoeErZIrLQtIvMfMrVb7b8oR7S+vM9DAyFdTOeQD3CIB8jZV8j2dK0Efp/Ez3faCqa0N2h2sHgyqTAYbPVjf7RAL5fdI6krDcMY/b1C2OGw=
  - secure: Ug3Nq3xbdrvyFJX7o+UL5t9QY8yojHQucVE824HpJuaQSw9CNL1DEk+jrBwnZZdEA70rXnpLTlHVet/lM37WnXqDGOWIEe+sNRO+87V87ONFpvnmzChScJjkATsbCaPAdeGpKSEm9JiRSMndDqKWALkHzTbHGmw9Q6w6bfzEePiJR72y3Qss92xfEkxsfivAsyYrkTt3JK1Uz68ol5HNJI2yx8Q8N+cZtE+hF8q6C/v206dea0UCZtKWDtTBFShLm88bSN7BcLiYM0aBLUBcpS5+mOg+6Gq0My/VPEvUVrBA8q900ys3xwv0JRYcD6cO02yYBimT/twy7i5xRAiitToU8AbyNJsPhjKWP+kGlKD/X2glNxZ5Pn90ZMf66cJY24juVnCFxoP3zNu+5WuTwIr3jLiR7ZXbEbb6Ti4gjzKYwl+FuW+oInq34D+5GyXonYmo2udDzwkPP92GISpWLLmTIoW6j99v3uaszZZBz/aVG4Jfol8qoBTZIZZ9TyRJjzvYIO6WluSvDL0wupPP4LlClsXbAI8bglnQjN5YPoAg+gysqmFHBrNRFnXm5Rr/zU19w8T/jAh4sdIenTBu7tXYgFsNCgTYBhDWsp8Mzc90NDIX6EKyCKVqR7k45PNjKB79ONxkL3SymdCcq84a+rWRgtNpAiaDZOI1Z1Xkv7o=
install: nvm install 8.3.0
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.atomist"
  - "$HOME/.npm"
deploy:
  provider: releases
  api_key:
    secure: L0gE4yiZ4GfLJ9eRk6kghUJxyfanbX6/vFJDo1bUgIXtIodZc3gKAxPr1kPCcf7xvhr3wRE6g2EYlF/Jq8D1N0zJL6ZqwwI+c2E5GXjGerhEhSg8NVbhBvRxfcTLFIN+cC5eNk4/9MB+vybzGj2odctyBwjq6bQm0+XLqoe6fnErCQ/AWBAhKaiRuPtisROYHO0Y/jSmr5yXCeMdllrgYgKurnxxhDYbQQavN0qvGVrXxUh1Y/L34r+DBLpC9RBT4LCdTYvLiwS0TaAjUgpsfphLosSQQV2diN5of0P2zC4ykrwdilaGHxKbLvdw11ikekvAi9W30eY6YJekFpGuJEUqReAzhUJz8nWRIBm0eb6oBoYnJFb7cW0zWlOJlgJlt5jkz8VJyhgQAB7jVSoOn7NrHbanBZRHPHLb6uKjPivgxqTZt7TOM0j8UMaenD5y1PQXAeWHFCGsQ3n6mKwJOdqvQkP9ZtNAIQ98nJ+ZaolX3yC8ude7eESO52nGCRKvbEdeLuZq9hPeHXeTQyCzHSVzSUvfykQ65oCz8zrOI591V7P7pa+JCdvONBMc68S2mT//+Db/Nw8L+QP+7vNoJfsNEKykC4g3HT1nntj70XbEa6KIcTGi97576Jyvvy2l7jozADqtLT7wKNiNPtd9z4B2SfNKmtkgWHgu7AMJGiI=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
