dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: eboSQKkvNsR4GzeH9vbypDIKKUqaLOtKcNudvoi2tE9nM70TztJj4op7GYK9D78lxLezGSgAqbvXa26kPmNbnDmjl8pmotEhsumWjYdZUQEe3ypnK5Yv931ahKdtmSXuVISfAPuUMCz1tf82N/4bDZc8vIzr4FOPZjpV36wZRahcRQijHGr/xuZ1jPaGwX6mGrSmn0wkdohVvlTfuElRPqb9wpabjneKPutFYMR7Vw4d9wIQdmYeL6/2j4aIWKcGxOGVCwRwam8S38oojEi1XTDPHHnUlABQjIo6KQfnYRsBqhNoGcTmKIuSwjyInuKkQHILK7AnofD8EgFEu/jdUjN/vm83FOLp1zfNoiYkDagWwFTgXaHa3WFoX97gzK7WchHrMy/5l6/ym33A0aMQrFAXqgXC7MwFGn80NDxCVw5N6T03PgWIVsR7wzH1xvPaEBxlZ8ozU/W/27yc25aRVYt5F3QuyV32qo3VKQCCzY9egzkxdoyOJB/VzH3HSB/mGCszfnqbZjL5zAYQWAu5g18w2iGTvF/TRVRjIIimyBXIrKyuXcSvIg97NbLr9xZsJ59DPKpBH3ztoHqAyaZjZ67tjB84WeAjdKaDKemcolU56TuSb5VevFW0TW83SaQ/OB9GPKchA9wR/PY4ju1v7MbpPckOrFRwZIyAU5/2OYw=
  - secure: SDp2lQm4iWFyeEijHdkeExivotvsySCMLDlsBuY47T+V+Mr+dKRTUTVCToP1lsRuqrE+rnDHPnDUYaIYfD2CRfqEM1FrdYhcL1knCNlex8KJyIPI8AYYRofFlYNjengG/tActt5C7H2k2MjjgTPChlIn3GTgz2sGaD9CirYfMDUYoECQlBhl69BetZg4rPQntEztyw43UviKik9aZVVvrT5kIeT7cJz8i2B9Si51imlWHQHrmJpahBjV9pPHvL/K3hAQ3htVPuXhHzY5keuzlCdglriYeFB7uTkcKtnz+DK2TNjGFBHSNDBWgn3AMBuzzEehK+5citeEhfi0qbA5u9LLeI5TT+vSTZ1/fdGnS51XIXuYNbTJHCbCvzqQiT1Ywxqir7rL+6nlL/0cV0I+Dtn48zuLxFoyUQN3Msuf+PrVB2WlgFxUrbw3IX1E+gG5uZfwZonXKYh1sBK5Ec0hv+jipy8TLEJTDkcdP1GOq4ttPllKYpLB8eMUl0QOIjX4t0OGtGS03Kj07ot3qi5hr9Xkexb/NY7LL/4sSW5Foku6dHKQqcC27vCeleyrzlibfSA+r5TyEZvMbULwtvHP1xP5/6UfSpor3xWrGTmzVRx2UW5Rb8U/JAQvWmd543NkM/qU8GSZx4pN2PQkjDF+J8u5wTz8YRW2dpWrEky+HgM=
  - secure: Of7Df3EtvzIU5VGPMntIVy/ZT8iEMvar4CxKBjyICzRxui+pPs/4k0j8SeRzcdRqhAHqTsfSf+COoo4jj2pQzEkeK04oBv/6cAIYNRabFlVo6pW2vGPzUQDJbykj6PSKzmwORq+wwRDiXkGiCvaA5SOvI5cCvjqaER7rI9LcS/nQ/lwvYUaXEEku2mt4jV4bgWAg223RTfwk7hcsVIXPxbauB08cZbJBNB/YbiYb20ijIOYFndBuEcQ8YSBfPzIyzAHHWhik2kL/8hZIwlfyvz1GrWuWyAj24Eq5NX8CIyDsKFVBmDvkZU6GLcY1rKITr0GsEOS0dbemeWZ4seKsx08tM8FMXYxz/3HyPiYCjtTOLezJfOd0z5O5IEkD1FKuR01wkBXtmDOlm4AE0EnRSCCEH+DZvVNIjsbAIdWJ3LxotYeKYF5JvxRjT7VavOM3BXXtRksuzpnNF7uLtI9f3ySePNvAtrWMV5VWMOvMiDgWeigK9mAx7RyvoZdbOPKr/Nt9KdT+i8o56ICT8phS/RbbRa6V7qlZQZE/gHyFZvr6sKMpxiw4s2Gjt6zvd8punoeErZIrLQtIvMfMrVb7b8oR7S+vM9DAyFdTOeQD3CIB8jZV8j2dK0Efp/Ez3faCqa0N2h2sHgyqTAYbPVjf7RAL5fdI6krDcMY/b1C2OGw=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
