# Copyright © 2017 Atomist, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


Feature: Tests from ConvertExistingProjectToRugArchive.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.


  Scenario: ConvertExistingProjectToRugArchive should add Rug archive files
    Given an empty project
    When ConvertExistingProjectToRugArchive for ConvertExistingProjectToRugArchive should add Rug archive files
    Then parameters were valid
    Then changes were made
    Then fileExists manifest for ConvertExistingProjectToRugArchive should add Rug archive files
    Then fileContains manifest artifact archiveName for ConvertExistingProjectToRugArchive should add Rug archive files
    Then fileContains manifest group groupId for ConvertExistingProjectToRugArchive should add Rug archive files
    Then fileContains manifest version for ConvertExistingProjectToRugArchive should add Rug archive files


  Scenario: ConvertExistingProjectToRugArchive should make no change if project already contains a manifest
    Given the archive root
    When ConvertExistingProjectToRugArchive archiveName is my-rug-archive, groupId is my-rug-group, version is 0.0.1 for ConvertExistingProjectToRugArchive should make no change if project already contains a manifest
    Then parameters were valid
    Then no changes were made
