# Copyright © 2017 Atomist, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


Feature: Tests from NewRugProject.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.


  Scenario: NewRugProjectSetParameters
    Given an empty project
    When NewRugProject for NewRugProjectSetParameters
    Then parameters were valid
    Then fileExists atomist manifest yml for NewRugProjectSetParameters
    Then fileContains atomist manifest yml version for NewRugProjectSetParameters
    Then fileContains atomist manifest yml pName for NewRugProjectSetParameters
    Then fileContains atomist manifest yml owner for NewRugProjectSetParameters
    Then not result fileExists CHANGELOG md for NewRugProjectSetParameters
    Then not result fileExists CODE OF CONDUCT md for NewRugProjectSetParameters
    Then not result fileExists travis yml for NewRugProjectSetParameters
    Then fileExists README md for NewRugProjectSetParameters
    Then fileContains README md pName for NewRugProjectSetParameters
    Then not result fileContains README md Atomist rug editors for NewRugProjectSetParameters
    Then fileContains README md description for NewRugProjectSetParameters
    Then not result fileContains README md editors to create a Rug archive project for NewRugProjectSetParameters
    Then not result fileContains README md AddTypeScript editor adds support files for NewRugProjectSetParameters
    Then fileContains README md https travis ci org owner pName svg branch master for NewRugProjectSetParameters
    Then fileContains README md not Slack Status https join atomist com badge svg https join atomist com for NewRugProjectSetParameters
    Then not result fileContains README md NewRugProject for NewRugProjectSetParameters
    Then not result fileContains README md ruggery for NewRugProjectSetParameters
    Then fileContains README md rug http docs atomist com for NewRugProjectSetParameters
    Then fileContains README md Support for NewRugProjectSetParameters
    Then fileContains README md Development for NewRugProjectSetParameters
    Then fileContains README md Created by Atomist atomist for NewRugProjectSetParameters
    Then fileContains README md Need Help Join our Slack team slack for NewRugProjectSetParameters


  Scenario: NewRugProjectDefaultParameters
    Given an empty project
    When NewRugProject for NewRugProjectDefaultParameters
    Then parameters were valid
    Then fileExists atomist manifest yml for NewRugProjectDefaultParameters
    Then fileContains atomist manifest yml 0 1 0 for NewRugProjectDefaultParameters
    Then fileContains atomist manifest yml pName for NewRugProjectDefaultParameters
    Then fileContains atomist manifest yml owner for NewRugProjectDefaultParameters
    Then not result fileExists CHANGELOG md for NewRugProjectDefaultParameters
    Then not result fileExists CODE OF CONDUCT md for NewRugProjectDefaultParameters
    Then not result fileExists travis yml for NewRugProjectDefaultParameters
    Then fileExists README md for NewRugProjectDefaultParameters
    Then fileContains README md pName for NewRugProjectDefaultParameters
    Then not result fileContains README md Atomist rug editors for NewRugProjectDefaultParameters
    Then fileContains README md description for NewRugProjectDefaultParameters
    Then not result fileContains README md editors to create a Rug archive project for NewRugProjectDefaultParameters
    Then not result fileContains README md AddTypeScript editor adds support files for NewRugProjectDefaultParameters
    Then fileContains README md https travis ci org owner pName svg branch master for NewRugProjectDefaultParameters
    Then fileContains README md not Slack Status https join atomist com badge svg https join atomist com for NewRugProjectDefaultParameters
    Then not result fileContains README md NewRugProject for NewRugProjectDefaultParameters
    Then not result fileContains README md ruggery for NewRugProjectDefaultParameters
    Then fileContains README md rug http docs atomist com for NewRugProjectDefaultParameters
    Then fileContains README md Support for NewRugProjectDefaultParameters
    Then fileContains README md Development for NewRugProjectDefaultParameters
    Then fileContains README md Created by Atomist atomist for NewRugProjectDefaultParameters
    Then fileContains README md Need Help Join our Slack team slack for NewRugProjectDefaultParameters
