Feature: Tests from TypeScriptEditor.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.




  Scenario: TypeScriptEditor is added to your project by AddTypeScriptEditor
    Given the archive root
    When TypeScriptEditor inputParameteristhe inputParameter value for TypeScriptEditor is added to your project by AddTypeScriptEditor
    Then parameters were valid
    Then changes were made
    Then fileContains hello txt Hello Worldnot for TypeScriptEditor is added to your project by AddTypeScriptEditor
