Feature: Tests from TypeScriptGenerator.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.


  Scenario: TypeScriptGenerator should create a new project based on this archive
    Given an empty project
    When TypeScriptGenerator for TypeScriptGenerator should create a new project based on this archive
    Then parameters were valid
    Then fileExists README md for TypeScriptGenerator should create a new project based on this archive
